import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider
  
        appearance={{
          elements: {
            organizationSwitcherPopoverRootBox: {
              width: "100%",
              pointerEvents: "auto",
            },
            userButtonPopoverRootBox: {
              width: "100%",
              pointerEvents: "auto",
            },
        
          },
        }}
      >
      <html lang="en">
        <body>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
